package jsfacile.read

import scala.collection.mutable
import scala.collection.mutable.ArrayBuffer

import jsfacile.joint.namedOrdering
import jsfacile.read.CoproductParser.{CpConsideredField, CpFieldInfo, CpProductInfo}

/** This class is used by the code generated by the macros that derive parsers for coproducts. It is not intended to be used by the library user.
 * It is used by said chunks of generated code, which are nothing but parser builders, to accumulate the information about the subtypes of `C` they need later to build the [[CoproductParser]] instance they return.
 * @tparam C the coproduct */
class CoproductParserBuilderState[C] {

	val productFieldsBuilder: mutable.ArrayBuffer[CpFieldInfo] = ArrayBuffer.empty;
	def addProductField(field: CpFieldInfo): Unit = productFieldsBuilder.addOne(field);
	def productFields: Array[CpFieldInfo] = productFieldsBuilder.sortInPlace()(namedOrdering[CpFieldInfo]).toArray;

	val consideredFieldsBuilder: mutable.ArrayBuffer[CpConsideredField] = ArrayBuffer.empty;
	def addConsideredField(consideredField: CpConsideredField): Unit = consideredFieldsBuilder.addOne(consideredField);
	def consideredFields: Array[CpConsideredField] = consideredFieldsBuilder.sortInPlace()(namedOrdering).toArray;

	val productsInfoBuilder: mutable.ArrayBuffer[CpProductInfo[C]] = ArrayBuffer.empty;
	def addProduct(product: CpProductInfo[C]): Unit = productsInfoBuilder.addOne(product)
	def productsInfo: Array[CpProductInfo[C]] = productsInfoBuilder.sortInPlace()(namedOrdering).toArray;
}
